### ISSUE TITLE
Add msys to path when installing MinGW

### ISSUE THREAD

**Issue by ChadH1971** [AICSC/Walkthrough#1]
This may be unnecessary complication. What you have done is beautiful. This issue came up towards the end of COMP B12, in the running of the in class hash, we used a switch, findMax or something like that. It was not a recognized command on my system until I placed msys into my path variable.

This is a hugely valuable set of instructions that if marketed (ie. tell Professor Mendoza about it and encourage him as AICSC adviser to let his students know about it) will save a lot of time and anguish. Very good job Pat.

**Comment by pathawks** [comment]
I will investigate.

Would be helpful if you could send me exactly what was not working, so that I can test around a bit.

**Comment by ChadH1971** [comment]
I'll see if I can back track through my notes. There are tools located in
msys that are not in the bin. Like I said, it may be complicating things
too much to add that step

**Comment by pathawks** [comment]
> Like I said, it may be complicating things too much to add that step

No, if it's important we should include it.

Unfortunately, I can't get screenshots at the moment because I'm in the middle of a _long_-running process on my Mac Pro, so I cannot boot into Windows 8. But, I can boot into Windows 7 on my laptop and test around to work up the instructions and whatnot.

**Comment by pathawks** [comment]
Oh wow!

Yeah, you're right. So I guess we also need to add `C:\MinGW\msys\1.0\bin` to the path? What a mess.

As an aside, in B13 Mendoza kept sending me scripts that I could not run on my Windows machine. Turns out, `awk` is part of **MSys**, which was not in my path.

**Comment by ChadH1971** [comment]
Doh! How is it that we become the bridge to success with Hal Mendoza?

**Comment by pathawks** [comment]
:stuck_out_tongue_winking_eye:

I'll get this changed just as soon as I can fix the screenshot.

**Comment by ChadH1971** [comment]
No hurry. Can you help me on something unrelated though. I need to learn
how to change my Web site for mobile versus desk top
